general {
# Prevent multiple hyprlock instances from spawning.
	lock_cmd = pidof hyprlock || hyprlock
# Screen locks before it suspends.
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
# Screen locks after 10 minutes.
	timeout = 600
# Lock screen when timeout has passed.
	on-timeout = loginctl lock-session
}

listener {
# Computer screen turns off after 20 minutes.
	timeout = 1200
# Screen off when timeout has passed.
	on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
# Screen on when activity is detected after timeout has fired.
	on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}

listener {
# Computer will suspend after 30 minutes.
	timeout = 1800
	on-timeout = systemctl suspend
}
