################
### Hyprlock ###
################
input-field {
# Main Settings
	size = 1800, 200
	outline_thickness = 2
	dots_size = 0.2
	dots_spacing = 0.2
	dots_center = true
	check_color = rgba(0, 0, 0, 0)
	outer_color = rgba(0, 0, 0, 0)
	inner_color = rgba(0, 0, 0, 0)
	font_color = rgba(161, 177, 227, 1)
	fade_on_empty = false
	font_family = "JetBrains Mono Nerd Font"
	placeholder_text =‿̩͙⊱༒︎༻ 😈 ⛧ 𝕰𝖓𝖙𝖊𝖗 𝖄𝖔𝖚𝖗 𝕻𝖆𝖘𝖘𝖜𝖔𝖗𝖉 ⛧ 🔒 ༺༒︎⊰‿̩͙
	dots_text_format =🤣
	hide_input = false
	position = 0, 0
	halign = center
	valign = center

# Fail Settings
	fail_color = rgba(220, 119, 134, 1)
	fail_text =【ＡＣＣＥＳＳ 🫩✌️🥀 ＤＥＮＩＥＤ】
}

background {
	path = ~/Pictures/Wallpapers/Waneella/red.png
	blur_size = 2
	blur_passes = 2
}
