# Bell Settings
enable_audio_bell	yes
bell_path		none

# Terminal Settings
background_opacity	0.5
allow_hyperlinks	yes

# Font Settings
# font_family		JetBrains Mono
# bold_font		auto
# italic_font		auto
# bold_italic_font	auto
font_size		10

# Cursor Settings
cursor_trail		2
cursor_shape		block

# BEGIN_KITTY_THEME
# E-Ink Dark
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font Mono' style=ExtraBold
bold_font        family='JetBrainsMono Nerd Font Mono' style=Bold
italic_font      family='JetBrainsMono Nerd Font Mono' style='Bold Italic'
bold_italic_font family='JetBrainsMono Nerd Font Mono' style='Bold Italic'
# END_KITTY_FONTS
