if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Standard plugins can be found in $ZSH/plugins/
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

### START of ALIASES
# Main
alias ls='eza -x --color=auto'
alias grep='grep --color=auto'
alias date="date +%D' '%A' '%r"
alias cal='khal calendar'
alias ff='kitten icat -n --align=left ~/Pictures/Fastfetch/green1FF.gif | fastfetch --raw - --config ~/.config/fastfetch/presets/main.jsonc'
alias yz='yazi'
alias klok='tty-clock -scbt'
alias bs='brightnessctl s'
alias start='start-hyprland'
# Configuration Files
alias kc='sudo nano ~/.config/kitty/kitty.conf'
alias hc='sudo nano ~/.config/hypr/hyprland.conf'
alias zc='sudo nano ~/.zshrc'
alias ffc='sudo nano ~/.config/fastfetch/config.jsonc'
# Language Translations
alias enl='trans en:nl'
alias nle='trans nl:en -b'
### END of ALIASES

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

wal -R
clear
